### ISSUE TITLE
[CONTRIBUTION] Add thisisatest container

### ISSUE THREAD

**Issue by Vbitz** [neurodesk/neurocontainers#1082]
### Add Container Request

**Container Name:** thisisatest
**Version:** 1.0.0

This is an automated contribution request to add the container recipe.

```yaml
name: thisisatest
version: 1.0.0
architectures:
  - x86_64
structured_readme:
  description: hello
  example: world
  documentation: testing
  citation: do not commit
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives: []
categories:
  - functional imaging
readme: |-
  ----------------------------------
  ## thisisatest/1.0.0 ##

  hello

  Example:
  \\\`\\\`\\\`
  world
  \\\`\\\`\\\`

  More documentation can be found here: testing

  Citation:
  \\\`\\\`\\\`
  do not commit
  \\\`\\\`\\\`

  To run container outside of this environment: ml thisisatest/1.0.0

  ----------------------------------

```

---
*This issue was generated automatically by the Neurocontainers Builder UI*
