### ISSUE TITLE
[CONTRIBUTION] Add donotmerge container

### ISSUE THREAD

**Issue by Vbitz** [neurodesk/neurocontainers#1088]
### Add Container Request

**Container Name:** donotmerge
**Version:** 1.0.0

This is an automated contribution request to add the container recipe.

```yaml
name: donotmerge
version: 1.0.0
architectures:
  - x86_64
structured_readme:
  description: Do not merge
  example: not to be merged
  documentation: ''
  citation: Not (Merge)
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives: []
categories:
  - programming
  - visualization
readme: |-
  ----------------------------------
  ## donotmerge/1.0.0 ##

  Do not merge

  Example:
  \\\`\\\`\\\`
  not to be merged
  \\\`\\\`\\\`

  More documentation can be found here: 

  Citation:
  \\\`\\\`\\\`
  Not (Merge)
  \\\`\\\`\\\`

  To run container outside of this environment: ml donotmerge/1.0.0

  ----------------------------------

```

---
*This issue was generated automatically by the Neurocontainers Builder UI*
